<a href="https://colab.research.google.com/github/Baudier13/NN/blob/main/practico_2_resuelto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Familiarizandose con **Numpy**

Referencias:
* https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python
* https://towardsdatascience.com/a-cheat-sheet-on-generating-random-numbers-in-numpy-5fe95ec2286

## **Ejercicio 1)** Importando librerías

Importe las librerías `numpy` para operar con arrays, `scipy` para operar con algebra lineal y `matplotlib.pyplot` para graficar.

In [ ]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

## **Ejercicio 2)** Creando arrays

**a)** Cree un array de enteros `a` a partir de la lista `[1,2,3]`.

**b)** Cree un array bidimensional de flotantes `b` a partir de la lista de listas `[[1.5,2,3],[4,5,6]]`.

**c)** Cree un array tridimensional de flotantes `b` a partir de la lista de listas `[[[1.5,2,3],[4,5,6]],[[3,2,1],[4,5,6]]]`.

In [ ]:
# 2.a)
a = np.array([1,2,3])
# 2.b)
b = np.array([[1.5,2,3],[4,5,6]], dtype = float)
# 2.c)
c = np.array([[[1.5,2,3],[4,5,6]],[[3,2,1],[4,5,6]]], dtype = float)

In [ ]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

## **Ejercicio 3)** Inicializamdo arrays

**a)** Utilice `np.zeros` para crear un array bidimensional de flotantes incializados a `0.0`, y de dimensiones de tamaños `(3,4)`.

**b)** Utilice `np.ones` para crear un array tridimensional de enteros inicializados a `1`, y de dimensiones `(2,3,4)`.

**c)** Utilice `np.arange` para crear un array `d` de valores enteros equiespaciados de a `5` entre `10` y `25`.

**d)** Utilice `np.linspace` para crear un array de `9` valores flotantes equiespaciados entre `0.0` y `9.0`.

**e)** Utilice `np.full` para crear un array bidimensional de entradas iguales a `7`, y de dimesiones `(2,2)`.

**f)** Utilice `np.eye` para crear una matriz identidad de dimensiones 2x2.

**g)** Utilice `np.random.random` para crear un array bidimensional de dimensiones 2x2 inicializado con valores aleatorios uniformemente sorteados del intervalo $[0,1]$.

**h)** Utilice `np.empty` para crear un array bidimensional sin inicializar y de dimensiones `(3,2)`.


In [ ]:
# 3.a)
np.zeros((3,4)) #Create an array of zeros
# 3.b)
np.ones((2,3,4),dtype=np.int16) #Create an array of ones
# 3.c)
d = np.arange(10,25,5)#Create an array of evenly spaced values (step value)
# 3.d)
np.linspace(0,2,9) #Create an array of evenlyspaced values (number of samples)
# 3.e)
e = np.full((2,2),7)#Create a constant array
# 3.f)
f = np.eye(2) #Create a 2X2 identity matrix
# 3.g)
np.random.random((2,2)) #Create an array with random values
# 3.h)
np.empty((3,2)) #Create an empty array

array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

## **Ejercicio 4)** Inspeccionando arrays

Considere los arrays de los ejercicios 2) y 3).

**a)** Utilizando `.shape`, determine cuales son las dimensiones del array `a`.

**b)** Utilizando la función `len()`, determine el *largo* del array `a`.

**c)** Utilizando `.ndim`, determine el número de dimensiones del array `b`.

**d)** Utilizando `.size`, determine el número de entradas que tienen `e`.

**e)** Utilizando `.dtype`, determine el tipo de los datos contenidos por el array `b`.

**f)** Utilizando `.dtype.name`, determine el nombre del tipo de los datos contenidos por el array `b`.

**g)** Utilizando `.astype`, convierta el array `b` a un array de tipo `int`.



In [ ]:
# 4.a)
a.shape #Array dimensions
# 4.b)
len(a)#Length of array
# 4.c)
b.ndim #Number of array dimensions
# 4.d)
e.size #Number of array elements
# 4.e)
b.dtype  #Data type of array elements
# 4.f)
b.dtype.name  #Name of data type
# 4.g)
b.astype(int) #Convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

## **Ejercicio 5)** Tipos de datos

**a)** Cree un array que contenga elementos de tipo `np.int64`.

**b)** Cree un array que contenga elementos de tipo `np.float32`.

**c)** Cree un array que contenga elementos de tipo `np.complex128`.

**d)** Cree un array que contenga elementos de tipo `np.bool`.

**e)** Cree un array que contenga elementos de tipo `np.object`.

**f)** Cree un array que contenga elementos de tipo `np.string_`.

**g)** Cree un array que contenga elementos de tipo `np.unicode_`.

In [ ]:
# 5.a)
np.array([1,2,3],dtype=np.int64)
# 5.b)
np.array([1,2,3],dtype=np.float32)
# 5.c)
np.array([1+3.j,2,3],dtype=complex)
# 5.d)
np.array([1,0,1],dtype=bool)
# 5.e)
np.array([1,"hola",[3,4]],dtype=object)
# 5.f)
np.array(["hola","mundo","argentina"],dtype=np.string_)
# 5.g)
np.array(["hola","mundo",'😀',u'\u03bcm'],dtype=np.unicode_)

array(['hola', 'mundo', '😀', 'μm'], dtype='<U5')

## **Ejercicio 6)** Operando sobre arrays

Considere los arrays de los ejercicios 2) y 3).

**a)** Calcule la resta `a-b` de los arrays `a` y `b` y almacene el resultado en un array `g`.

**b)** Notar que `a` y `b` poseen diferentes dimensiones (i.e., `a.shape` es distinto de `b.shape`) y, sin embargo, en el inciso anterior numpy computa la suma `a+b`. Explique lo que ocurre.

**c)** Compare el anterior resultado con el uso de `np.substract`.

**d)** Calcule la suma `a-b` de los arrays `a` y `b`.

**e)** Compare el anterior resultado con el uso de `np.add`.

**f)** Calcule la división punto a punto  `a/b` de `a` y `b`.

**g)** Compare el anterior resultado con el uso de `np.divide`.

**h)** Calcule la multiplicación punto a punto  `a*b` de `a` y `b`.

**i)** Compare el anterior resultado con el uso de `np.multiply`.

**j)** Calcule la exponencial punto a punto  `np.exp(b)` de `b`.

**k)** Calcule la raíz cuadrada punto a punto  `np.sqrt(b)` de `b`.

**l)** Calcule el seno punto a punto  `np.sin(a)` de `a`.

**m)** Calcule el coseno punto a punto  `np.sin(b)` de `b`.

**n)** Calcule el logaritmo natural punto a punto  `np.log(a)` de `a`.

**o)** Calcule el producto punto `e.dot(f)` entre `e` y `f`.

**p)** Compare el anterior resultado con el uso de `np.dot`.

**q)** Explique las diferentes opciones que puede adoptar el producto punto de numpy según el número de dimensiones que tengan sus factores.

Ayuda: use https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [ ]:
# 6.a)
g = a - b #Subtraction

###  Rta. 6.b)

Explicarlo en la pizarra. Mirar:

   https://numpy.org/doc/stable/reference/generated/numpy.add.html

   https://www.yaohong.vip/post/python/numpyadd/

In [ ]:
# 6.c)
np.subtract(a,b) #Subtraction
# 6.d)
b + a #Addition 
# 6.e)
np.add(b,a) #Addition 
# 6.f)
a/b #Division 
# 6.g)
np.divide(a,b) #Division 
# 6.h)
a * b #Multiplication 
# 6.i)
np.multiply(a,b) #Multiplication 
# 6.j)
np.exp(b) #Exponentiation
# 6.k)
np.sqrt(b) #Square root
# 6.l)
np.sin(a)  #Print sines of an array
# 6.m)
np.cos(b) #Elementwise cosine
# 6.n)
np.log(a)#Elementwise natural logarithm
# 6.o)
e.dot(f) #Dot product 
# 6.p)
np.dot(e,f) #Dot product 

array([[7., 7.],
       [7., 7.]])

 ### Rta. 6.q)

 Explicarlo en la pizarra

## **Ejercicio 7)** Comparando arrays

**a)** Use `==` para realizar una compación punto a punto de los arrays `a` y `b`.

**b)** Use `<` para realizar una comparación punto a punto del array `b` con el escalar `2`.

**c)** Use `np.array_equal(a,b)` para determinar si `a` y `b` son iguales como arrays.

In [ ]:
# 7.a)
a == b #Elementwise comparison
# 7.b)
a < 2 #Elementwise comparison
# 7.c)
np.array_equal(a, b) #Arraywise comparison

False

## **Ejercicio 8)** *Copiando* arrays

**a)** Use `.view()` para crear una vista del array `a`.

**b)** Use `.copy()` para crear una copa del array `a`.

In [ ]:
# 8.a)
h = a.view()#Create a view of the array with the same data
# 8.b.1)
np.copy(a) #Create a copy of the array
# 8.b.2)
h = a.copy() #Create a deep copy of the array

## **Ejercicio 9)** Ordenado

**a)** Use `.sort()` para ordenar los elementos de `a`.

**b)** Ordene los elementos de `a` a lo largo del eje `0`. Explique.

In [ ]:
# 9.a)
a.sort() #Sort an array
# 9.b)
c.sort(axis=0) #Sort the elements of an array's axis

In [ ]:
z = np.array([[4,2,6],[3,1,5]])

In [ ]:
z

array([[4, 2, 6],
       [3, 1, 5]])

In [ ]:
z.sort(axis=0)
z

array([[3, 1, 5],
       [4, 2, 6]])

In [ ]:
z.sort(axis=1)
z

array([[1, 3, 5],
       [2, 4, 6]])

## **Ejercicio 10)** Indexado y *slicing* (rebanado) de arrays

**a)** Seleccione el segundo elemento de `a`.

**b)** Seleccione el elemento en la fila 1 y columna 2 de `b`.

Si `n` y `m` son enteros, luego `[n:m]` indica el rango de índices que van desde `n` hasta `m-1`.

**c)** Seleccione el rango `[0:2]` de elementos de `a`.

**d)** Seleccione los elementos de `b` en el rango `[0:2]` de filas de `a` y la columna `1`.

**e)** Seleccione todos los elementos de `b` que esten en el rango de filas `[0:1]` y el rango completo de columnas.

**f)** Uso de *elipsis*. Seleccione los elementos de `c` indexados por `[1,...]`. Es esto lo mismo que lo indexado por `[1,:,:]`?

Si `n`, `m` y `s` son enteros, luego `[n:m:s]` indica el rango de índices que van desde `n` hasta `m-1` saltando de a `s` elementos.

**g)** Utilice lo mencionado anteriormente para acceder a los elementos de `a` de forma invertida.

**h)** Seleccione los elementos de `a` que sean menores que dos. 

**i)** Seleccione los elementos de `b` indicados por la lista de índices `[(1,0),(0,1),(1,2),(0,0)]` utilizando, correspondientemente, una lista de indices fila y una lista de índices columna.

**j)** Utilizando una lista de indices fila, seleccione las filas `1,0,1,0` de `b`, y luego, para cada selección anterior, utilice una lista de índices columna para seleccionar las columnas `0,1,2,0`.

In [ ]:
z = [1,2,3,4,5,6,7,8,9]
z[::-2]

[9, 7, 5, 3, 1]

In [ ]:
# 10.a)
a[2] #Select the element at the 2nd index
# 10.b)
b[1,2] #Select the element at row 1 column 2(equivalent to b[1][2])

# 10.c)
a[0:2]#Select items at index 0 and 1
# 10.d)
b[0:2,1] #Select items at rows 0 and 1 in column 1
# 10.e)
b[:1] #Select all items at row0(equivalent to b[0:1, :])
# 10.f)
c[1,...] #Same as[1,:,:]
# 10.g)
a[ : : -1] #Reversed array a array([3, 2, 1])

# 10.h)
a[a<2] #Select elements from a less than 2

# 10.i)
b[[1,0,1, 0],[0,1, 2, 0]] #Select elements(1,0),(0,1),(1,2) and (0,0)
# 11.j)
b[[1,0,1, 0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows and columns

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## **Ejercicio 11)** transposición

**a)** Use `np.transpose()` para calcular la traspuesta del array `b`, y asignarlo a una variable `i`.

**b)** Use `.T` para acceder a `i` de forma traspuesta. Es esta forma traspuesta igual a `b`?

In [ ]:
# 11.a)
i = np.transpose(b) #Permute array dimensions
# 11.b)
i.T #Permute array dimensions

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## **Ejercicio 12)** Redimensionado

**a)** Use `.ravel()` para *achatar* el array `b`.

**b)** Use `.reshape()` para redimensionar el array `g` de manera que adquiera dimensiones especificadas por la tupla `(3,-2)`. 

**c)** Que indica aquí el signo negativo del segundo índice?

In [ ]:
# 12.a)
b.ravel() #Flatten the array
# 12.b)
g.reshape(3, -1) #Reshape, but don’t change data

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

In [ ]:
# 12.c) Un sólo índice negativo indica usar el tamaño que que falta en la 
# dimensión correspondiente para completar el tamaño total del array.
z = np.array([[1,2,3],[4,5,6]])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
z.shape

(2, 3)

In [ ]:
z.reshape(3,-2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
z.reshape(-3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
w = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
w

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [ ]:
w.shape

(3, 2, 3)

In [ ]:
w.reshape(-1,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [ ]:
#w.reshape(-1,-1,2)

## **Ejercicio 13)** Agregando y quitando elementos

**a)** Use `np.resize()` para crear a partir del array `h` un nuevo array de tamaño y dimensiones diferentes indicadas por `(2,6)`.

**b)** Use `np.append()` para crear un nuevo array que agrege los elementos de `g` al final de los elementos de `h`. Notar que `h` y `g` tienen diferentes dimensiones. Cómo resuelve `numpy` esta cuestión?

**c)** Use `np.insert()` para crear una copia de `a` en donde se inserta el número `5` en la posición indexada por `1`.

**d)** Use `np.delete()` para eliminar los elementos de `a` indicados por la lista de índices `[1]`.

In [ ]:
# 13.a)
np.resize(h,(2,6)) #Return a new arraywith shape(2,6)
# 13.b)
np.append(h,g) #Append items to an array
# 13.c)
np.insert(a,1,5)  #Insert items in an array
# 13.d)
np.delete(a,[1])  #Delete items from an array

array([1, 3])

## **Ejercicio 14)** Combinando arrays

**a)** Use `np.concatenate()` para concatenar los arrays `a` y `d`.

**b)** Use `np.vstack()` para apilar verticalmente los arrays `a` y `b`.

**c)** Use `np.row_stack()` para apilar verticalmente los arrays `e` y `f`.

**d)** Use `np.hstack()` para apilar horizontalmente los arrays `e` y `f`.

**e)** Use `np.column_stack()` para apilar horizontalmente los arrays `a` y `d`.

In [ ]:
# 14.a)
np.concatenate((a,d),axis=0) #Concatenate arrays
# 14.b)
np.vstack((a,b)) #Stack arrays vertically(row wise)
# 14.c)
np.row_stack([e,f]) #Stack arrays vertically(row wise)
# 14.d)
np.hstack([e,f]) #Stack arrays horizontally(column wise)
# 14.e)
np.column_stack((a,d)) #Create stacked column wise arrays

## **Ejercicio 15)** *Separando* arrays

**a)** Use `np.hsplit()` para separar horizontalmente el array `a` en 3 partes. 

**b)** Use `np.vsplit()` para separar verticalmente el array `c` en 2 partes.

**c)** Cree el array `z` dado por 

  [[1, 2, 3, 4],
   [2, 0, 0, 2],
   [3, 1, 1, 0]]

y sepárelo en dos partes a lo largo del eje `1`.

In [ ]:
# 15.a)
np.hsplit(a,3) #Split the array horizontally at the 3rd index
# 15.b)
np.vsplit(c,2) #Split the array vertically at the 2nd index
# 15.c)
# create a 2d numpy array
z = np.array([[1, 2, 3, 4],
              [2, 0, 0, 2],
              [3, 1, 1, 0]])
# split the array into 2 subarrays horizontally
sub_arrays = np.split(arr, 2, axis=1)
# display the sub_arrays
sub_arrays

NameError: ignored

## **Ejercicio 16)** Generando números aleatorios

**a)** Use `np.random.random()` para generar un número aleatorio de tipo float64 a partir de la distribución uniforme en $[0,1]$.

**b)** Use `np.random.random()` para crear un array de 10 números aleatorios de tipo float64 generados a partir de la distribución uniforme en $[0,1]$.

**c)** Use `np.random.random()` para crear un array dos dimensional de dimensiones `(3,4)` conteniendo números aleatorios de tipo float64 generados a partir de la distribución uniforme en $[0,1]$.

**d)** Use `np.random.randn()` para generar un número aleatorio de tipo float64 a partir de la distribución normal centrada en $\mu=0$ y de varianza $\sigma^2=1$. 

**e)** Use `np.random.randn()` para generar un número aleatorio de tipo float64 a partir de la distribución normal centrada en $\mu=5$ y de varianza $\sigma^2=9$.

**f)** Use `np.random.randn()` para generar un array de dimensiones `(3,2,3)` conteniendo números aleatorios de tipo float64 generados a partir de la distribución normal centrada en $\mu=-1$ y de varianza $\sigma^2=2$.

**g)** Use `np.random.randint()` para generar un número aleatorio de tipo int64 a partir de la distribución uniforme en $\{0,1,2,3\}$.

**h)** Use `np.random.randint()` para generar un número aleatorio de tipo int64 a partir de la distribución uniforme en $\{10,11,12,13,14,15\}$.

**i)** Use `np.random.randint()` para generar un array de dimensiones `(3,2,3)` conteniendo números aleatorios de tipo int64 generados a partir de la distribución uniforme en $\{0,1\}$.

**j)** Use `np.random.choice()` para seleccionar uniformemente al azar un elemento de la lista `["perro","gato","loro","caballo","vaca"]`.

**k)** Use `np.random.choice()` para crear un array de dimensiones `(3,3)` con selecciones generadas uniformemente al azar de los elementos de la lista `["perro","gato","loro","caballo","vaca"]`.

**l)** Use `np.random.choice()` para crear un array de dimensiones `(3,3,3)` con selecciones generadas al azar de los elementos de la lista `["perro","gato","loro","caballo","vaca"]` de acuerdo a la correspondiente lista de probabilidades `[8/16,4/16,2/16,1/16,1/16]`.

**m)** Use `np.random.permutation()` generar una permutación, seleccionada uniformemente al azar una de las `n!` permutaciones que existen de un conjunto de `n` elementos, de una la lista de números entre `0` y `n-1` para `n=10` denominada `lista_n`.

**n)** Repita lo anterior usando `np.random.shuffle()` para aleatorizar la lista `lista_n` *in situ*.

In [ ]:
# 16.a)
np.random.random()
# 16.b)
np.random.random(10)
# 16.c)
np.random.random((3,4))
# 16.d)
np.random.randn()
# 16.e)
3.*np.random.randn()+5.
# 16.f)
np.sqrt(2)*np.random.randn(3,2,3)-1.
# 16.g)
np.random.randint(4)
# 16.h)
np.random.randint(10,16)
# 16.i)
np.random.randint(0,2,(3,2,3))
# 16.j)
np.random.choice(["perro","gato","loro","caballo","vaca"])
# 16.k)
np.random.choice(["perro","gato","loro","caballo","vaca"],size=(3,3))
# 16.l)
np.random.choice(["perro","gato","loro","caballo","vaca"],size=(3,3,3),p=[8/16,4/16,2/16,1/16,1/16])
# 16.m)
lista_n = np.arange(10)
np.random.permutation(lista_n)
# 16.n)
np.random.shuffle(lista_n)
lista_n

array([1, 2, 6, 3, 7, 4, 9, 0, 8, 5])